# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.network :private_network, ip: "192.168.200.120"
  # config.vm.network :public_network
  config.vm.hostname = "vagrant-demo"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo -e '#{File.read("#{Dir.home}/.ssh/id_rsa.pub")}' >> '/home/vagrant/.ssh/authorized_keys'

    sudo sed -i '/deb-src/d' /etc/apt/sources.list
    sudo sed -i 's/archive.ubuntu.com/mirrors.163.com/' /etc/apt/sources.list
    sudo sed -i 's/security.ubuntu.com/mirrors.163.com/' /etc/apt/sources.list
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
    sudo apt-get update

    sudo apt-get install -y vim git tmux exuberant-ctags python-virtualenv python-pip bpython httpie
    sudo apt-get install -y libssl-dev libpython-dev libmysqlclient-dev libffi-dev
    sudo apt-get install -y nodejs npm

    # wget https://raw.githubusercontent.com/elvis-macak/config-repo/master/install.sh
    # sh install.sh
  SHELL

end
